### ISSUE TITLE
Some devDependencies should be full-fledged dependencies ?

### ISSUE THREAD

**Issue by NickCrews** [j0lv3r4/mdx-prism#8]
Hi! Thanks for this library. I'm using it in my [personal website](https://github.com/NickCrews/blahg) and this is quite helpful.

I'm not a NPM/js/etc expert, but I believe that many of the `devDependencies` you have listed in `package.json` should actually be `dependencies`, since you use them in `index.js`. I discovered this when I recently added the `depcheck` package to my website as a linting check, and it told me that I wasn't using the `rehype` package that I had listed as one of my dev dependencies. So, following its advice, I did `yarn remove rehype`,  rebuilt my website, and got:

```
Error: Cannot find module 'rehype'
Require stack:
- /Users/nickcrews/Documents/projects/blahg/node_modules/mdx-prism/index.js
- /Users/nickcrews/Documents/projects/blahg/.next/server/pages/blog.js
...
```

If I understand correctly, before I was getting lucky because although `mdx-prism` wasn't installing `rehype` for itself, it was able to traverse up the `node_modules/` tree and find the `rehype` that was installed for my website.

So I think really all of the includes in `index.js` should be moved from dev to normal dependencies. I can submit a PR if you want.

**Comment by NickCrews** [comment]
There's a PR that I think fixes this.

**Comment by NickCrews** [comment]
Also I found that the `depcheck` linter would catch this problem. When I run that on your broken main branch it says
```
nickcrews@Nicks-MBP mdx-prism % npx depcheck --ignores=husky
Missing dependencies
* unified: ./index.js
* rehype-parse: ./index.js
```
After that PR then `depcheck` passes

**Comment by j0lv3r4** [comment]
closed by https://github.com/j0lv3r4/mdx-prism/pull/9

**Comment by NickCrews** [comment]
Sweet, thanks! Any idea when you'll release v0.3.4 (that has this fix) to npmjs.com?

**Comment by NickCrews** [comment]
v0.3.4 is released on https://www.npmjs.com/package/mdx-prism
